apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-nginx
  name: sample-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
